USE [BlogDb]

-- Додати категорії
INSERT INTO [BlogDb].[dbo].[Categories] ([Name], [Description])
VALUES 
('Adventure', 'Exciting journeys and explorations.'),
('Budget Travel', 'Traveling with minimal expenses.'),
('Luxury Travel', 'Exclusive and premium travel experiences.'),
('Family Travel', 'Trips and vacations for families.'),
('Solo Travel', 'Exploring the world on your own.'),
('Road Trips', 'Journeys on the open road.'),
('Nature Escapes', 'Connecting with nature.'),
('Beach Holidays', 'Relaxation by the sea.'),
('Mountain Getaways', 'Exploring the peaks and valleys.'),
('Cultural Journeys', 'Immersive cultural experiences.'),
('City Breaks', 'Short trips to urban destinations.'),
('Wellness Retreats', 'Focus on health and relaxation.'),
('Wildlife Safaris', 'Exploring natural habitats.'),
('Food & Culinary', 'Traveling for gastronomic delights.'),
('Historical Travels', 'Discovering historical sites.'),
('Extreme Sports', 'Adrenaline-pumping adventures.'),
('Eco-Tourism', 'Sustainable and green travel.'),
('Winter Escapes', 'Snowy destinations and activities.'),
('Photography Trips', 'Capturing moments and landscapes.'),
('Festivals & Events', 'Experiencing global celebrations.');

-- Додати хештеги
INSERT INTO [BlogDb].[dbo].[Hashtags] ([Name])
VALUES 
('#Adventure'),
('#Backpacking'),
('#BudgetTravel'),
('#LuxuryTravel'),
('#FamilyAdventures'),
('#SoloTravel'),
('#RoadTrips'),
('#NatureLovers'),
('#BeachDays'),
('#MountainAdventures'),
('#CulturalExperience'),
('#CityExploration'),
('#WellnessRetreat'),
('#Safari'),
('#FoodieTravels'),
('#HistoricalSites'),
('#ExtremeAdventures'),
('#EcoTravel'),
('#WinterWonders'),
('#TravelPhotography'),
('#FestivalHopping'),
('#HiddenGems'),
('#TravelTips'),
('#WorldExplorer'),
('#IslandHopping'),
('#UrbanAdventures'),
('#HikingTrails'),
('#BeachVibes'),
('#OffTheBeatenPath'),
('#CulturalHeritage'),
('#CityLife'),
('#RelaxAndUnwind'),
('#WildlifeAdventures'),
('#FoodLovers'),
('#HistoryBuff'),
('#ExtremeSports'),
('#EcoFriendlyTravel'),
('#SnowAdventures'),
('#ScenicRoutes'),
('#FestivalFun'),
('#LocalCuisine'),
('#TravelInspiration'),
('#TropicalParadise'),
('#WildernessExploration'),
('#ArtAndCulture'),
('#TravelGoals'),
('#Wanderlust'),
('#TravelBucketList'),
('#ScenicViews'),
('#AdventureAwaits');
